### ISSUE TITLE
Oracle query decoding throws `Invalid checksum`

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-sdk-js#1078]
**Describe the bug**
When trying to decode an oracle query using `Crypto.decodeBase64Check()` the 

**To Reproduce**
1. Run this example oracle script and prefund it with some testnet ae: https://github.com/mradkov/ae-oracle-pricefeed/tree/invalid_query
2. Deploy [this contract](https://github.com/mradkov/ae-oracle-pricefeed/blob/invalid_query/PriceFeedQueryFixedOracle.aes) on testnet with the `ok_...` address of your oracle as `init` argument.
3. Use `contracts.aeternity.art` or other web GUI to interact with the contract to send a contractCallTx to the `queryAePrice` method with any string as argument. eg. `exa` with `200000000000000` as value (fee for the oracle).
4. Open your oracle logs and see error:

```
{
  fee: 200000000000000,
  id: 'oq_panB7VboPBNk8FtzqqsHp5wwZQRAX2fvroVeK1VnUndtrFZ2t',
  oracleId: 'ok_63dfUPCCrpmU3bjyx7qkzz3yuBFpHgAN6W7jZn2TKxQgM8apD',
  query: 'ov_ZXhhkLf6zw==',
  response: 'or_Xfbg4g==',
  responseTtl: { type: 'delta', value: 20 },
  senderId: 'ak_7ezDQhrSQoX5HCCoVLWP8bnLpbEwqyFBYbFctUp2wCbaw9Vki',
  senderNonce: 3,
  ttl: 331479
}
(node:96898) UnhandledPromiseRejectionWarning: Error: Invalid checksum
    at Module.gr (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:74370)
    at respond (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/src/priceFeedOracle.js:97:31)
    at /Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:244144
    at s (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:18015)
    at Generator._invoke (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:17768)
    at Generator.forEach.t.<computed> [as next] (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:18372)
    at n (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:2458)
    at i (/Users/milenradkov/projects/blockchain/aeternity/ae-oracle-pricefeed/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:2669)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:96898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:96898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
Crypto.decodeBase64Check() should be working correctly to decode the oracle query.

**Screenshots**

**Please tell us about your environment:**
  
  - Node Version: v12.14.1
  - Protocol Version: 1
  - Compiler version: v0.0.0
  - VM Version: fate
  - SDK Version: v7.7.0
  - Python version: v2.7

**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

This is being decoded succcesfully using the node encoder via cli:

```
(aeternity_ct@localhost)14> aeser_api_encoder:decode(<<"ov_ZXhhkLf6zw==">>).  
{oracle_query,<<"exa">>}
```

**Comment by davidyuk** [comment]
You can't pass the whole oracle query to `decodeBase64Check` because it is prefixed with `ov_`.

```
> Crypto.decodeBase64Check('ZXhhkLf6zw==')
<Buffer 65 78 61>
> Crypto.decodeBase64Check('ZXhhkLf6zw==').toString()
'exa'
```
does it work for you?

**Comment by mradkov** [comment]
> You can't pass the whole oracle query to `decodeBase64Check` because it is prefixed with `ov_`.
> 
> ```
> > Crypto.decodeBase64Check('ZXhhkLf6zw==')
> <Buffer 65 78 61>
> > Crypto.decodeBase64Check('ZXhhkLf6zw==').toString()
> 'exa'
> ```
> 
> does it work for you?

Yes, it does, thanks.

Though it will be nice to have this handled by the SDK somehow, as the regular user cannot possibly know they need to slice the prefix in order to decode the query? 🤔 
`Crypto.decodeBase64Check(query.query.slice(3)).toString()`

**Comment by davidyuk** [comment]
In this case, I think the best is to decode on the sdk side automatically. There shouldn't be any cases when the user needs the encoded value.

**Comment by davidyuk** [comment]
it is implemented in https://github.com/aeternity/aepp-sdk-js/blob/2b25e5dc944eb338fb1ad01d73649879ed4362cf/src/oracle.ts#L111-L112
