### ISSUE TITLE
serving docs fails

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1094]
On current `develop`, running `mkdocs serve` quits with the following error: 

```

> @aeternity/aepp-sdk@7.7.0 docs:api /Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js
> node apidoc.js

/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/lib/jsdoc-command.js:114
      throw err
      ^

JSDOC_ERROR: [
    at ExplainSync.verifyOutput (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/lib/jsdoc-command.js:112:19)
    at ExplainSync._runJsdoc (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/lib/explain-sync.js:31:32)
    at ExplainSync.getOutput (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/lib/explain-sync.js:12:21)
    at ExplainSync.execute (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/lib/jsdoc-command.js:49:24)
    at Object.explainSync (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-api/index.js:29:18)
    at JsdocToMarkdown.getJsdocDataSync (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-to-markdown/index.js:131:21)
    at JsdocToMarkdown.getTemplateDataSync (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/node_modules/jsdoc-to-markdown/index.js:101:28)
    at Object.<anonymous> (/Users/nick/Documents/DAPPS/Aeternity/aepp-sdk-js/apidoc.js:28:31)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  name: 'JSDOC_ERROR'
}
```

@davidyuk could you quickly hook me up about the things you added to the mkdocs since i created it to make troubleshooting easier ?

**Comment by davidyuk** [comment]
The major change is that mkdocs runs scripts to generate md files from our code before doing his job.

As I see, the `docs:api` script fails in your environment with an unclear error, I can't reproduce it. Try to run this:

```bash
git clone git@github.com:aeternity/aepp-sdk-js.git
cd aepp-sdk-js
npm i
npm run docs:api
```

As a workaround, you can remove [these lines](https://github.com/aeternity/aepp-sdk-js/blob/b688a96bf5c3f550bfa9736f17fcc66e8816d8f0/docs/hooks.py#L7-L8) before running `mkdocs serve`.

**Comment by nikita-fuchs** [comment]
works, thanks.
