### ISSUE TITLE
make integration tests in CI deterministic

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1288]
currently some integration tests always randomly fail

**Comment by subhod-i** [comment]
@marc0olo @davidyuk @mradkov 

Failed tests are previous runs:

First run:
```
1) Channel
 can solo close a channel:
     Error: Giving up after 10 blocks mined, transaction hash: th_2vRTZT6GtJYzHyLj3RDikKrhiVPHDj4iYSZp2TLpKk6JHkVBxn
      at Object._callee10$ (src/chain/node.js:14:6669)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
      at _next (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Second run:
```
1) Channel
       can dispute via slash tx:
     Error: Giving up after 10 blocks mined, transaction hash: th_CheTzzwYfdzMYvupYUjvxB1rUhRp2gBZbc21k8Mz7XZt8VZPD
      at Object._callee10$ (src/chain/node.js:14:6669)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
      at _next (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Thrid run
```
  1) Generalize Account
       Init MemoryAccount for GA and Spend using GA:
     Error: Bad Request
      at http (node_modules/swagger-client/lib/http.js:106:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Fourth run
```
 1) Channel
       can reconnect:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/aepp-sdk-js/aepp-sdk-js/test/integration/channel.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)  
```

Fifth run:
```
  1) Channel
       can solo close a channel:
     Error: Giving up after 10 blocks mined, transaction hash: th_2rdMFv6vppqdVARWhVA2EZCmAmjYrG3V1qHYumhtP4ZJgSwmn
      at Object._callee10$ (src/chain/node.js:14:6669)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
      at _next (node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) Channel
       throws errors
         "before all" hook for "when posting an update with negative amount":
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/aepp-sdk-js/aepp-sdk-js/test/integration/channel.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by subhod-i** [comment]
Although PR #1299 expected to solve this issue but the issue still persists
