### ISSUE TITLE
SDK13 and 14 have issues with decoding addresses in react

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-sdk-js#2029]
**Describe the bug**

When running a contract call (static or stateful) where the parameter or return value is an address the following error is produced:

```
base58check.js:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'decode')
    at Object.decode (base58check.js:19:1)
    at ApiEncoder.decode (ApiEncoder.js:79:1)
    at ApiEncoder.decodeWithType (ApiEncoder.js:106:1)
    at InternalMapper.toAddress (InternalMapper.js:39:1)
    at InternalMapper.toInternal (InternalMapper.js:20:1)
    at ExternalDataFactory.create (ExternalDataFactory.js:12:1)
    at CompositeDataFactory.js:36:1
    at Array.map (<anonymous>)
    at ExternalDataFactory.createMultiple (CompositeDataFactory.js:36:1)
    at CallDataFactory.create (CallDataFactory.js:19:1)
```

**To Reproduce**

https://github.com/kenodressel/sdk-react-issue

**Expected behavior**

I would love to do any contract call.

**Please tell us about your environment:**

- Node Version: v20-v23 tested
- Protocol Version: 7.1
- Compiler version: latest
- SDK Version: v13 + v14

CC: @thepiwo @yusufseyrek

**Comment by davidyuk** [comment]
should be fixed by https://github.com/aeternity/aepp-calldata-js/pull/296
related issue https://github.com/facebook/create-react-app/issues/12700

**Comment by yusufseyrek** [comment]
When should we expect this to be fixed?

**Comment by davidyuk** [comment]
It works with the new [release of calldata](https://github.com/aeternity/aepp-calldata-js/releases/tag/v1.9.0)
In the above reproduction I did `npm i @aeternity/aepp-calldata@1.9.0` and it worked after that
