### ISSUE TITLE
SyntaxError of Unexpected identifier

### ISSUE THREAD

**Issue by Gaseema** [aeternity/aepp-sdk-js#273]
I'm getting SyntaxError of Unexpected identifier while trying to import Ae. Could you kindly assist me with this.

My app.js file contains the line of code below
-- import Ae from '@aeternity/aepp-sdk/es/ae/universal'

Error is as follows (unexpected identifier is "Ae")

import Ae from '@aeternity/aepp-sdk/es/ae/universal' // or any other flavor
SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by ricricucit** [comment]
Hi @Gaseema, since this seems to be correct can you give us steps to reproduce this...or even better: some repository we can check out?
