### ISSUE TITLE
Channel deposit seems to be failing

### ISSUE THREAD

**Issue by tenuki** [aeternity/aepp-sdk-js#586]
Channel deposit seems to be failing

## Expected Behavior
Channel.deposit(..) performs deposit as expected

## Current Behavior
it seems to be failing before placing deposit tx on chain..

```
Error: Unexpected message received:

{"jsonrpc":"2.0","method":"channels.info","params":{"channel_id":"ch_2ejBP5ZQAXw5Gw9HXtxaP4iNm7k4MhPqBiQSj3u5gNQScstrMY","data":{"event":"died"}},"version":1}
    at Ru (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:184368)
    at fp (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:194644)
    at /home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:181523
    at u (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:16339)
    at Generator._invoke (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:16127)
    at Generator.t.(anonymous function) [as next] (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:16761)
    at n (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:2256)
    at c (/home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:2466)
    at /home/aweil/repos/ea/hubservice/hub/tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:2525
    at new Promise (<anonymous>)
  wsMessage:
   { jsonrpc: '2.0',
     method: 'channels.info',
     params:
      { channel_id: 'ch_2ejBP5ZQAXw5Gw9HXtxaP4iNm7k4MhPqBiQSj3u5gNQScstrMY',
        data: [Object] },
     version: 1 } }
State channel: disconnected

```

## Steps to Reproduce
1. execute provided script

## Environment / Context

-server side
-@aeternity/aepp-sdk@4.3.0
-forgae ae node @latest when @aeternity/aepp-sdk@4.3.0 was released

**Comment by tenuki** [comment]
```
const {Channel, Universal, TxBuilder: {unpackTx}} = require('@aeternity/aepp-sdk')
const {BigNumber} = require('bignumber.js')

const NODEHOST = "10.10.0.79";
const API_URL = 'http://'+NODEHOST+':3001'
const INTERNAL_API_URL = 'http://'+NODEHOST+':3001'
const STATE_CHANNEL_URL = 'ws://'+NODEHOST+':3001/channel'
const NETWORK_ID = 'ae_docker'
const RESPONDER_HOST = 'localhost'
const RESPONDER_PORT = 3001

const initiatorAddress = 'ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU'
const responderAddress = 'ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk'

let initiatorAccount
let responderAccount

async function createAccounts() {
    initiatorAccount = await Universal({
        networkdId: NETWORK_ID,
        url: API_URL,
        internalUrl: INTERNAL_API_URL,
        keypair: {
            publicKey: initiatorAddress,
            secretKey: 'bb9f0b01c8c9553cfbaf7ef81a50f977b1326801ebf7294d1c2cbccdedf27476e9bbf604e611b5460a3b3999e9771b6f60417d73ce7c5519e12f7e127a1225ca'
        }
    })
    console.log("account1: ", initiatorAddress, await initiatorAccount.balance(initiatorAddress))
    responderAccount = await Universal({
        networkdId: NETWORK_ID,
        url: API_URL,
        internalUrl: INTERNAL_API_URL,
        keypair: {
            publicKey: responderAddress,
            secretKey: '7c6e602a94f30e4ea7edabe4376314f69ba7eaa2f355ecedb339df847b6f0d80575f81ffb0a297b7725dc671da0b1769b1fc5cbe45385c7b5ad1fc2eaf1d609d'
        }
    })
    console.log("account2: ", responderAddress, await responderAccount.balance(responderAddress))
}

async function initiatorSign(tag, tx) {
    console.log("isign:", tag, tx)
    if (tag === 'initiator_sign') {
        return initiatorAccount.signTransaction(tx)
    }

    // Deserialize binary transaction so we can inspect it
    const {txType, tx: txData} = unpackTx(tx)
    if (tag === 'shutdown_sign_ack') {
        // Fee amount is splitted equally per participants
        const fee = BigNumber(txData.fee).div(2)
        if (
            txType === 'channelCloseMutual' &&
            // To keep things simple we manually check that
            // balances are correct (as a result of previous transfer update)
            BigNumber(txData.initiatorAmountFinal).plus(fee).eq(BigNumber(DEPOSIT).minus(10)) &&
            BigNumber(txData.responderAmountFinal).plus(fee).eq(BigNumber(DEPOSIT).plus(10))
        ) {
            return initiatorAccount.signTransaction(tx)
        }
    }
    console.log("****  unsigned:", tag, tx)
}

async function responderSign(tag, tx, {updates} = {}) {
    console.log("rsign:", tag, tx)
    if (tag === 'responder_sign') {
        return responderAccount.signTransaction(tx)
    }

    // Deserialize binary transaction so we can inspect it
    const {txType, tx: txData} = unpackTx(tx)
    // When someone wants to transfer a tokens we will receive
    // a sign request with `update_ack` tag
    if (tag === 'update_ack') {
        // Check if update contains only one offchain transaction
        // and sender is initiator
        if (
            txType === 'channelOffChain' &&
            updates.length === 1 &&
            updates[0].op === 'OffChainTransfer' &&
            updates[0].from === initiatorAddress
        ) {
            return responderAccount.signTransaction(tx)
        }
    }

    if(tag === "deposit_ack") {
        return responderAccount.signTransaction(tx)
    }
    if(tag === "withdraw_ack") {
        return responderAccount.signTransaction(tx)
    }
    console.log("****  unsigned:", tag, tx)
}

async function connectAsInitiator(params) {
    return Channel({
        ...params,
        url: STATE_CHANNEL_URL,
        role: 'initiator',
        sign: initiatorSign
    })
}

async function connectAsResponder(params) {
    return Channel({
        ...params,
        url: STATE_CHANNEL_URL,
        role: 'responder',
        sign: responderSign
    })
}

const DEPOSIT = 1000000000000000000
const params = {
    // Public key of initiator
    // (in this case `initiatorAddress` defined earlier)
    initiatorId: initiatorAddress,
    // Public key of responder
    // (in this case `responderAddress` defined earlier)
    responderId: responderAddress,
    // Initial deposit in favour of the responder by the initiator
    pushAmount: 0,
    // Amount of tokens initiator will deposit into state channel
    initiatorAmount: DEPOSIT,
    // Amount of tokens responder will deposit into state channel
    responderAmount: DEPOSIT,
    // Minimum amount both peers need to maintain
    channelReserve: 40000,
    // Minimum block height to include the channel_create_tx
    ttl: 1000,
    // Amount of blocks for disputing a solo close
    lockPeriod: 10,
    // Host of the responder's node
    host: RESPONDER_HOST,
    // Port of the responders node
    port: RESPONDER_PORT,
}

createAccounts().then(() => {
    // initiator connects to state channels endpoint
    connectAsInitiator(params).then(async initiatorChannel => {
        initiatorChannel.on('statusChanged', async (status) => {
            console.log('State channel:', status)
            if (status === 'open') {
                console.log('State channel has been opened!')
            }
        })

        initiatorChannel.on('onChainTx', (tx) => {
            console.log('channel_create_tx:', tx)
        })

        initiatorChannel.sendMessage('hello world', responderAddress)

        the_result = null;
        try{
            the_result = await initiatorChannel.update(
                // Sender account
                initiatorAddress,
                // Recipient account
                responderAddress,
                // Amount
                10,
                // This function should verify offchain transaction
                // and sign it with initiator's private key
                async (tx) => initiatorAccount.signTransaction(tx)
            );
        } catch(err) {
            console.log("UOPDATE ERR:", err);
        }

        if (the_result.accepted) {
            console.log('Succesfully transfered 10 tokens!')
        } else {
            console.log('Transfer has been rejected')
        }


        try{
            console.log("TESTING deposit")
            the_result = await initiatorChannel.deposit(
                10, async (tx) => await initiatorAccount.signTransaction(tx), {
                    onOnChainTx: (tx) => {console.log(" 1 on chain tx..")},
                    onOwnDepositLocked: (tx) => {console.log(" 2 onOwnDepositLocked")},
                    onDepositLocked: (tx) => {console.log(" 3 onDepositLocked")}});
            console.log("the result:", the_result);
        } catch(err) {
            console.log("deposit ERR:", err); 
        }



        console.log("initiator balance:", await initiatorChannel.balances([initiatorAddress]));
        try{
            console.log("TESTING withdraw..")
            the_result = await initiatorChannel.withdraw(
                1, async (tx) => await initiatorAccount.signTransaction(tx), {
                    onOnChainTx: (tx) => {console.log(" 1 on chain tx..")},
                    onOwnWithdrawLocked: (tx) => {console.log(" 2 onOwnWithdrawLocked")},
                    onWithdrawLocked: (tx) => {console.log(" 3 onWithdrawLocked")}});
            console.log("the result:", the_result);
        } catch(err) {
            console.log("withdraw ERR:", err); 
        }

        initiatorChannel.on('error', err => console.log(err))
    }).catch(err => {
        console.log('Initiator failed to connect!?')
        console.log(err)
    })

    // responder connects to state channels endpoint
    connectAsResponder(params).then(async responderChannel => {
        responderChannel.on('message', (msg) => {
            console.log('Received message from:', msg.from)
            console.log(msg.info)
        })

        // close channel after a minute
        setTimeout(() => {
            console.log('Closing channel...')
            responderChannel.shutdown(
                // This function should verify shutdown transaction
                // and sign it with responder's secret key
                async (tx) => responderAccount.signTransaction(tx)
            ).then((tx) => {
                console.log('State channel has been closed')
                console.log('You can track this transaction onchain', tx)
            }).catch(err => console.log(err))
        }, 60000)

        responderChannel.on('error', err => console.log(err))
    }).catch(err => {
        console.log('Responder failed to connect')
        console.log(err)
    })
})

```

**Comment by mpowaga** [comment]
Can't replicate. Below is the output I get when run the script provided (only difference is that I connect to the node through localhost).

```
account1:  ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU 12184216975126200000001
account2:  ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk 9000000000000000000
State channel: accepted
isign: initiator_sign tx_+IcyAaEB6bv2BOYRtUYKOzmZ6Xcbb2BBfXPOfFUZ4S9+EnoSJcqIDeC2s6dkAAChAVdfgf+wope3cl3GcdoLF2mx/Fy+RThce1rR/C6vHWCdiA3gtrOnZAAAgpxACgCGG0jrV+AAwKAJCKrnhdm18wowfhXGrvlvM35XgrjdCbKVZqIy1DPA8A33Bp8r
rsign: responder_sign tx_+IcyAaEB6bv2BOYRtUYKOzmZ6Xcbb2BBfXPOfFUZ4S9+EnoSJcqIDeC2s6dkAAChAVdfgf+wope3cl3GcdoLF2mx/Fy+RThce1rR/C6vHWCdiA3gtrOnZAAAgpxACgCGG0jrV+AAwKAJCKrnhdm18wowfhXGrvlvM35XgrjdCbKVZqIy1DPA8A33Bp8r
State channel: signed
channel_create_tx: tx_+QETCwH4hLhAKV0X4PGCRlMzdtNVioVjIbN7cumLVQXZWStENGGKakIIl9NwMt0A4ZxP9d0/oA0YB3BvRsoLZxN1tMpkEmLBB7hAzMLVdzTr5gBupZvqsLbqZsm1vOHluvKdZhsZC31JqO2Q7WHV2H97lNFfBgPdndA99JNQjEE/d2fMdqM9ni/lBbiJ+IcyAaEB6bv2BOYRtUYKOzmZ6Xcbb2BBfXPOfFUZ4S9+EnoSJcqIDeC2s6dkAAChAVdfgf+wope3cl3GcdoLF2mx/Fy+RThce1rR/C6vHWCdiA3gtrOnZAAAgpxACgCGG0jrV+AAwKAJCKrnhdm18wowfhXGrvlvM35XgrjdCbKVZqIy1DPA8A3ybncn
State channel: open
State channel has been opened!
Received message from: ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU
hello world
rsign: update_ack tx_+EY5AqEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hYCoPFwljQIYjV8YhUjwtrJUi/2spUBIvpTtPFvheoYqaVFhkPpEQ==
Succesfully transfered 10 tokens!
TESTING deposit
rsign: deposit_ack tx_+HQzAaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAem79gTmEbVGCjs5mel3G29gQX1zznxVGeEvfhJ6EiXKCoID6IYbSOtX4ACg394u6EP3A259RaPdbTSjfbbzWwk7o2SW+OnfDQ6Q5dkDDlSMS+Y=
 1 on chain tx..
 1 on chain tx..
 2 onOwnDepositLocked
 3 onDepositLocked
the result: { accepted: true,
  signedTx: 'tx_+QEACwH4hLhAV02mAaRvY9IB2frP0MHOvhUAl0YGLOnOYYjWjAcZaVWkJyjTHRwGS27shoUp4+nV55zFeQqyzxugICFiPgmvCbhA2UYKz3B7EGrP3pkZXCzD+w7KQYWvqHZBjjTVB4B2B/0fQiTfqRQ5mI/fJh2Uzm5bdjHQ3Awj9XyBxYBc+mPOBLh2+HQzAaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAem79gTmEbVGCjs5mel3G29gQX1zznxVGeEvfhJ6EiXKCoID6IYbSOtX4ACg394u6EP3A259RaPdbTSjfbbzWwk7o2SW+OnfDQ6Q5dkDDnm386Q=' }
initiator balance: { ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU: 1000000000000000000 }
TESTING withdraw..
rsign: withdraw_ack tx_+HQ0AaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAem79gTmEbVGCjs5mel3G29gQX1zznxVGeEvfhJ6EiXKAYID6IYbSOtX4ACgbxpiMpYJerwXvRXOHH1gjCgzln0RQK1v0NuNWXZK2hgED+3d5R4=
 1 on chain tx..
 1 on chain tx..
 2 onOwnWithdrawLocked
 3 onWithdrawLocked
the result: { accepted: true,
  signedTx: 'tx_+QEACwH4hLhAfGFNhZTLPeHTCV5Hjfo6FubcmI0FX5Hl2fVdCRIE0BmqLx1I40FUj7iUp65mJB39soMer9G4rcVyFHJ3jlC0CrhAfaqstiBbcJdtL6zZBqn1dkOduiKibH1MugPsP5gA6FMXtW9TWFvTeRBPiou7nyvzaCjp5RVHWhtd664cRweJDrh2+HQ0AaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAem79gTmEbVGCjs5mel3G29gQX1zznxVGeEvfhJ6EiXKAYID6IYbSOtX4ACgbxpiMpYJerwXvRXOHH1gjCgzln0RQK1v0NuNWXZK2hgED5lhr+E=' }
Closing channel...
isign: shutdown_sign_ack tx_+GE1AaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAVdfgf+wope3cl3GcdoLF2mx/Fy+RThce1rR/C6vHWCdiA3gqQ8xuA//iA3gqQ8xuBAKAIYbSOtX4AABj8oSSg==
****  unsigned: shutdown_sign_ack tx_+GE1AaEG2VxBWKx5IA5ET6nl77v2gJWhnWHr9IBcrTGVjGgy0hahAVdfgf+wope3cl3GcdoLF2mx/Fy+RThce1rR/C6vHWCdiA3gqQ8xuA//iA3gqQ8xuBAKAIYbSOtX4AABj8oSSg==
```

@tenuki Can you also provide aeternity node logs?

**Comment by tenuki** [comment]
Problem is related to invalid ttl specified.
