### ISSUE TITLE
balance method: Throw more clear exception if account was not used before

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#592]
Right now if I'm calling `sdk.balance('<address that was not used before>')` or `sdk.api.getAccountByPubkey('<address that was not used before>')
`
I'm receiving an exception:
```
TypeError: While calling getAccountByPubkey (pubkey), Cannot read property 'data' of undefined TypeError: While calling getAccountByPubkey (pubkey), Cannot read property 'data' of undefined
    at Object._callee$ (webpack-internal:///./node_modules/@aeternity/aepp-sdk/es/utils/swagger.js:540:101)
From previous event:
    at Object._callee2$ (webpack-internal:///./node_modules/@aeternity/aepp-sdk/es/chain/node.js:212:56)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:21)
From previous event:
    at Object.getAccount (webpack-internal:///./node_modules/@aeternity/aepp-sdk/es/chain/node.js:178:22)
    at Object._callee3$ (webpack-internal:///./node_modules/@aeternity/aepp-sdk/es/chain/node.js:247:25)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:21)
From previous event:
    at Object.balance (webpack-internal:///./node_modules/@aeternity/aepp-sdk/es/chain/node.js:225:19)
    at <anonymous>:1:45
    at <anonymous>:2:3
```
Would be better to throw something like "Account didn't make any transactions" or some 404 error, to distinguish it with some internal exception of SDK.

**Comment by nduchak** [comment]
@davidyuk Which node you are using?
 Can not repro it on my side, i am getting another error.
```
 Error: While calling getAccountByPubkey (pubkey), GET to http://localhost:3013/v2/accounts/ak_2YThfoBDRfB8Sg5pzc25MRPFBp3PbrbmsiEniARvP5YGAggf1W failed with 404: Account not found

```

**Comment by davidyuk** [comment]
I have this issue on both sdk-testnet.aepps.com and sdk-mainnet.aepps.com, I'm using 4.3.0 in browser.

**Comment by davidyuk** [comment]
I can reproduce "Account not found" exception in example aepp, probably we have broke SDK somehow on our side.

**Comment by davidyuk** [comment]
lately, we have defined custom error handler for Axios, we are not throwing exceptions from there. So SDK assumes that the request was successful and fails on the next step.
Was it intentioned behavior to make possible error swallowing from the global error handler?

**Comment by nduchak** [comment]
Mostly yes, but it will be better if we prevent this swallowing and just throw the error anyway.

**Comment by nduchak** [comment]
Do you have in mind some use cases when we need to swallow it?

**Comment by davidyuk** [comment]
No, I don't have, I agree that better to throw the error anyway

**Comment by nduchak** [comment]
https://github.com/aeternity/aepp-sdk-js/pull/607
