### ISSUE TITLE
example/identity depends on the not available version of SDK

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#899]
https://github.com/aeternity/aepp-sdk-js/blob/c5fa163a6411e09f304702ae3b9e31caf17b93de/examples/browser/vuejs/connect-two-ae/identity/package.json#L16

**Comment by nduchak** [comment]
Thanks for opening. Will fix it soon

**Comment by davidyuk** [comment]
Also, I can't build identity example after updating of sdk:

<details>
  <summary>Console log</summary>
  
```bash
$ git reset HEAD --hard
HEAD is now at b70c79fb Merge pull request #888 from aeternity/release/7.0.0
$ npm i @aeternity/aepp-sdk@7.0.0

> fsevents@1.2.11 install /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> websocket@1.0.31 install /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> core-js@2.6.11 postinstall /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.4 postinstall /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

+ @aeternity/aepp-sdk@7.0.0
added 1494 packages from 638 contributors and audited 20029 packages in 47.315s

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm run build

> base-and-contracts-aepp-examples@0.1.0 build /Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity
> NODE_ENV='prod' webpack -p


  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


TypeError: Class constructor TailwindExtractor cannot be invoked without 'new'
    at extractSelectors (/Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/purgecss/lib/purgecss.js:1:2420)
    at PurgeCSS.extractSelectorsFromFiles (/Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/purgecss/lib/purgecss.js:1:5864)
    at async PurgeCSS.purge (/Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/purgecss/lib/purgecss.js:1:8317)
    at async PurgeCSSPlugin.runPluginHook (/Users/denis/Documents/aepp-sdk-js/examples/browser/vuejs/connect-two-ae/identity/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:1:2299)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! base-and-contracts-aepp-examples@0.1.0 build: `NODE_ENV='prod' webpack -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the base-and-contracts-aepp-examples@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/denis/.npm/_logs/2020-02-17T14_23_28_168Z-debug.log
```  
</details>

**Comment by davidyuk** [comment]
This was not changed in #903:

https://github.com/aeternity/aepp-sdk-js/blob/f2d5e6c1eb6dec3364b72d7e7a69cf1bc239135b/examples/browser/vuejs/connect-two-ae/identity/package.json#L16
